version: "3.8"

services:
  web:
    build: .
    container_name: faheem_app
    command: ["fastapi", "run", "faheem/server.py"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: ./faheem
          target: /app/faheem

  db:
    image: postgres:13
    container_name: faheem_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
