artifact_uri: /Users/mamdouh_malaa/Developer/others/Faheem/tmp/mlflow/959873662289025224/b289c2ea6a4b4edf9bed15edf1506b5a/artifacts
end_time: 1717788623044
entry_point_name: ''
experiment_id: '959873662289025224'
lifecycle_stage: active
run_id: b289c2ea6a4b4edf9bed15edf1506b5a
run_name: traveling-snake-810
run_uuid: b289c2ea6a4b4edf9bed15edf1506b5a
source_name: ''
source_type: 4
source_version: ''
start_time: 1717788608363
status: 3
tags: []
user_id: mamdouh_malaa
