artifact_uri: /Users/mamdouh_malaa/Developer/others/Faheem/tmp/mlflow/959873662289025224/4cf1d9ebcb054aada8127436bb9af3d2/artifacts
end_time: 1718702158915
entry_point_name: ''
experiment_id: '959873662289025224'
lifecycle_stage: active
run_id: 4cf1d9ebcb054aada8127436bb9af3d2
run_name: bouncy-sow-657
run_uuid: 4cf1d9ebcb054aada8127436bb9af3d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1718702142328
status: 4
tags: []
user_id: mamdouh_malaa
