artifact_location: /Users/mamdouh_malaa/Developer/others/Faheem/tmp/mlflow/371059876512173790
creation_time: 1717796630547
experiment_id: '371059876512173790'
last_update_time: 1717796630547
lifecycle_stage: active
name: MultinomialNB Experiment with RandomizedSearchCV
